language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --dev --prefer-dist

script: vendor/bin/phpunit --configuration phpunit.xml.dist

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
